export const showList = { showList : [{ id: 80,
    url: 'https://www.tvmaze.com/shows/80/modern-family',
    name: 'Modern Family',
    type: 'Scripted',
    language: 'English',
    genres: [Array],
    status: 'Running',
    runtime: 30,
    premiered: '2009-09-23',
    officialSite: 'https://abc.go.com/shows/modern-family',
    schedule: [Object],
    rating: [Object],
    weight: 99,
    network: [Object],
    webChannel: null,
    externals: [Object],
    image: [Object],
    summary:
     '<p><b>Modern Family</b> revolves around three different types of families (nuclear, step- and same-sex) living in the Los Angeles area, who are interrelated through Jay Pritchett and his children, Claire Dunphy (née Pritchett) and Mitchell Pritchett. Patriarch Jay is remarried to a much younger woman, Gloria Delgado Pritchett (née Ramirez), a passionate Colombian with whom he has an infant son, Fulgencio (Joe) Pritchett, and a son from Gloria\'s previous marriage, Manny Delgado.</p><p>Jay\'s daughter Claire was a homemaker, but has returned to the business world. She is now the chief executive of her father\'s previous business, Pritchett\'s Closets and Blinds. She is married to Phil Dunphy, a realtor and self-professed "cool dad". They have three children: Haley Dunphy, a stereotypical ditzy teenage girl; Alex Dunphy, a nerdy, smart middle child; and Luke Dunphy, the off-beat only son.</p><p>Jay\'s lawyer son Mitchell and his husband Cameron Tucker have one daughter, Lily Tucker-Pritchett. As the name suggests, this family represents a modern-day family, and episodes are comically based on situations which many families encounter in real life.</p>',
    updated: 1578982924,
    _links: [Object] },
  { id: 2,
    url:
     'https://www.tvmaze.com/shows/23/once-upon-a-time-in-wonderland',
    name: 'Once Upon a Time in Wonderland',
    type: 'Scripted',
    language: 'English',
    genres: [Array],
    status: 'Ended',
    runtime: 60,
    premiered: '2013-10-10',
    officialSite: null,
    schedule: [Object],
    rating: [Object],
    weight: 0,
    network: [Object],
    webChannel: null,
    externals: [Object],
    image: [Object],
    summary:
     '<p>In Victorian England, the young and beautiful Alice tells a tale of a strange new land that exists on the other side of a rabbit hole. An invisible cat, a hookah smoking caterpillar and playing-cards that talk are just some of the fantastic things she\'s seen during this impossible adventure. Surely this troubled girl must be insane, and her doctors aim to cure her with a treatment that will make her forget everything. Alice seems ready to put it all behind her, especially the painful memory of the genie she fell in love with and lost forever -- the handsome and mysterious Cyrus . But deep down Alice knows this world is real, and just in the nick of time the sardonic Knave of Hearts and the irrepressible White Rabbit arrive to save her from a doomed fate. Together the trio will take a tumble down the rabbit hole to this Wonderland where nothing is impossible.</p>',
    updated: 1575358030,
    _links: [Object] },
  { id: 3,
    url: 'https://www.tvmaze.com/shows/62/the-originals',
    name: 'The Originals',
    type: 'Scripted',
    language: 'English',
    genres: [Array],
    status: 'Ended',
    runtime: 60,
    premiered: '2013-10-03',
    officialSite: 'https://www.cwtv.com/shows/the-originals/',
    schedule: [Object],
    rating: [Object],
    weight: 87,
    network: [Object],
    webChannel: null,
    externals: [Object],
    image: [Object],
    summary:
     '<p><b>The Originals</b> is a spin-off show from the supernatural drama <i>The Vampire Diaries</i>. It is based in the city of New Orleans where the originals represent the original vampires. The show is primarily based around conflict between vampires, werewolves and witches in the city.</p>',
    updated: 1575540921,
    _links: [Object] },
  { id: 4,
    url: 'https://www.tvmaze.com/shows/48/madam-secretary',
    name: 'Madam Secretary',
    type: 'Scripted',
    language: 'English',
    genres: [Array],
    status: 'Ended',
    runtime: 60,
    premiered: '2014-09-21',
    officialSite: 'https://www.cbs.com/shows/madam-secretary/',
    schedule: [Object],
    rating: [Object],
    weight: 100,
    network: [Object],
    webChannel: null,
    externals: [Object],
    image: [Object],
    summary:
     '<p><b>Madam Secretary</b> follows Elizabeth McCord, the shrewd, determined, newly appointed Secretary of State who drives international diplomacy, battles office politics and circumvents protocol as she negotiates global and domestic issues, both at the White House and at home. A college professor and a brilliant former CIA analyst who left for ethical reasons, Elizabeth returns to public life at the request of the President following the suspicious death of her predecessor. The President values her apolitical leanings, her deep knowledge of the Middle East, her flair for languages and her ability to not just think outside the box, but to not even acknowledge there is a box.</p>',
    updated: 1576063638,
    _links: [Object] },
  { id: 5,
    url: 'https://www.tvmaze.com/shows/208/the-chair',
    name: 'The Chair',
    type: 'Reality',
    language: 'English',
    genres: [],
    status: 'Ended',
    runtime: 60,
    premiered: '2014-09-06',
    officialSite: null,
    schedule: [Object],
    rating: [Object],
    weight: 0,
    network: [Object],
    webChannel: null,
    externals: [Object],
    image: [Object],
    summary:
     '<p><b>The Chair</b> is a competition documentary series that follows two directors through the process of bringing their first feature to the screen. The up-and-coming directors, who have unique backgrounds and skill sets, will be provided with an identical screenplay which they must craft as their own film. <i>The Chair</i> will document the creation, marketing and theatrical release of both adaptations, which will also air on STARZ. Both directors will be given the same budget, and both versions will use locations in the same city. Through multiplatform voting, the audience will determine which director will be awarded $250,000.</p>',
    updated: 1573497558,
    _links: [Object] },
  { id: 6,
    url: 'https://www.tvmaze.com/shows/171/how-i-met-your-mother',
    name: 'How I Met Your Mother',
    type: 'Scripted',
    language: 'English',
    genres: [Array],
    status: 'Ended',
    runtime: 30,
    premiered: '2005-09-19',
    officialSite: 'https://www.cbs.com/shows/how_i_met_your_mother',
    schedule: [Object],
    rating: [Object],
    weight: 95,
    network: [Object],
    webChannel: null,
    externals: [Object],
    image: [Object],
    summary:
     '<p><b>How I Met Your Mother</b> is a comedy about Ted and how he fell in love. It all starts when Ted\'s best friend, Marshall drops the bombshell that he\'s going to propose to his long-time girlfriend, Lilya kindergarten teacher. At that moment, Ted realizes that he had better get a move on if he too hopes to find true love. Helping him in his quest is Barney a friend with endless, sometimes outrageous opinions, a penchant for suits and a foolproof way to meet women. When Ted meets Robin he\'s sure it\'s love at first sight, but destiny may have something else in store.</p>',
    updated: 1573150338,
    _links: [Object] },
  { id: 7,
    url: 'https://www.tvmaze.com/shows/52/how-to-get-away-with-murder',
    name: 'How to Get Away with Murder',
    type: 'Scripted',
    language: 'English',
    genres: [Array],
    status: 'Running',
    runtime: 60,
    premiered: '2014-09-25',
    officialSite: 'https://abc.go.com/shows/how-to-get-away-with-murder',
    schedule: [Object],
    rating: [Object],
    weight: 98,
    network: [Object],
    webChannel: null,
    externals: [Object],
    image: [Object],
    summary:
     '<p>The brilliant, charismatic and seductive Professor Annalise Keating gets entangled with four law students from her class, <b>How to Get Away with Murder</b>. Little do they know that they will have to apply what they learned to real life, in this masterful, sexy, suspense-driven legal thriller.</p>',
    updated: 1577255126,
    _links: [Object] },
  { id: 8,
    url: 'https://www.tvmaze.com/shows/236/gcb',
    name: 'GCB',
    type: 'Scripted',
    language: 'English',
    genres: [Array],
    status: 'Ended',
    runtime: 60,
    premiered: '2012-03-04',
    officialSite: 'https://abc.go.com/shows/gcb',
    schedule: [Object],
    rating: [Object],
    weight: 0,
    network: [Object],
    webChannel: null,
    externals: [Object],
    image: [Object],
    summary:
     '<p>Amanda Vaughn once the ultimate high school "mean girl", is forced to return home in disgrace after her marriage ends in scandal. Amanda is nothing like the girl she was 20 years ago, but as her old classmates reacquaint themselves with the new Amanda, will her home town welcome her with open arms or seek revenge? No one in this town is a saint, but that doesn\'t mean they can\'t have a heart. As Amanda and her teenage kids try to adjust to their new lives, the ladies from her past alternate between sympathy and scheming.</p>',
    updated: 1573226209,
    _links: [Object] },
  { id: 9,
    url: 'https://www.tvmaze.com/shows/31/marvels-agents-of-shield',
    name: 'Marvel\'s Agents of S.H.I.E.L.D.',
    type: 'Scripted',
    language: 'English',
    genres: [Array],
    status: 'Running',
    runtime: 60,
    premiered: '2013-09-24',
    officialSite: 'https://abc.go.com/shows/marvels-agents-of-shield',
    schedule: [Object],
    rating: [Object],
    weight: 99,
    network: [Object],
    webChannel: null,
    externals: [Object],
    image: [Object],
    summary:
     '<p>Phil Coulson heads an elite team of fellow agents with the worldwide law-enforcement organization known as S.H.I.E.L.D. (Strategic Homeland Intervention Enforcement and Logistics Division), as they investigate strange occurrences around the globe. Its members -- each of whom brings a specialty to the group -- work with Coulson to protect those who cannot protect themselves from extraordinary and inconceivable threats.</p>',
    updated: 1574328665,
    _links: [Object] },
  { id: 10,
    url: 'https://www.tvmaze.com/shows/124/2-broke-girls',
    name: '2 Broke Girls',
    type: 'Scripted',
    language: 'English',
    genres: [Array],
    status: 'Ended',
    runtime: 30,
    premiered: '2011-09-19',
    officialSite: 'https://www.cbs.com/shows/2_broke_girls/',
    schedule: [Object],
    rating: [Object],
    weight: 91,
    network: [Object],
    webChannel: null,
    externals: [Object],
    image: [Object],
    summary:
     '<p><b>2 Broke Girls</b> is a comedy about two young women waitressing at a greasy spoon diner who strike up an unlikely friendship in the hopes of launching a successful business - if only they can raise the cash. Sassy, streetwise Max Black works two jobs just to get by, one of which is waiting tables during the night shift at the retro-hip Williamsburg Diner. Sophisticated Caroline Channing is an uptown trust fund princess who\'s having a run of bad luck that forces her to reluctantly give waitressing a shot. At first, Max sees Caroline as yet another in a long line of inept servers she must cover for, but she\'s surprised to find that Caroline has as much substance as she does style.</p><p>When Caroline discovers Max\'s knack for baking amazing cupcakes, she sees a lucrative future for them, but first they need to raise the start-up money. While they save their tips, they\'ll stay at the restaurant, working with Oleg, an overly flirtatious Russian cook; Earl, a 75-year-old kool-kat cashier; and Han Lee, the new, eager-to-please owner of the diner. Working together, these two broke girls living in one expensive city might just find the perfect recipe for their big break.</p>',
    updated: 1573517220,
    _links: [Object] },
    { id: 11,
      url: 'https://www.tvmaze.com/shows/80/modern-family',
      name: 'Modern Family',
      type: 'Scripted',
      language: 'English',
      genres: [Array],
      status: 'Running',
      runtime: 30,
      premiered: '2009-09-23',
      officialSite: 'https://abc.go.com/shows/modern-family',
      schedule: [Object],
      rating: [Object],
      weight: 99,
      network: [Object],
      webChannel: null,
      externals: [Object],
      image: [Object],
      summary:
       '<p><b>Modern Family</b> revolves around three different types of families (nuclear, step- and same-sex) living in the Los Angeles area, who are interrelated through Jay Pritchett and his children, Claire Dunphy (née Pritchett) and Mitchell Pritchett. Patriarch Jay is remarried to a much younger woman, Gloria Delgado Pritchett (née Ramirez), a passionate Colombian with whom he has an infant son, Fulgencio (Joe) Pritchett, and a son from Gloria\'s previous marriage, Manny Delgado.</p><p>Jay\'s daughter Claire was a homemaker, but has returned to the business world. She is now the chief executive of her father\'s previous business, Pritchett\'s Closets and Blinds. She is married to Phil Dunphy, a realtor and self-professed "cool dad". They have three children: Haley Dunphy, a stereotypical ditzy teenage girl; Alex Dunphy, a nerdy, smart middle child; and Luke Dunphy, the off-beat only son.</p><p>Jay\'s lawyer son Mitchell and his husband Cameron Tucker have one daughter, Lily Tucker-Pritchett. As the name suggests, this family represents a modern-day family, and episodes are comically based on situations which many families encounter in real life.</p>',
      updated: 1578982924,
      _links: [Object] },
    { id: 12,
      url:
       'https://www.tvmaze.com/shows/23/once-upon-a-time-in-wonderland',
      name: 'Once Upon a Time in Wonderland',
      type: 'Scripted',
      language: 'English',
      genres: [Array],
      status: 'Ended',
      runtime: 60,
      premiered: '2013-10-10',
      officialSite: null,
      schedule: [Object],
      rating: [Object],
      weight: 0,
      network: [Object],
      webChannel: null,
      externals: [Object],
      image: [Object],
      summary:
       '<p>In Victorian England, the young and beautiful Alice tells a tale of a strange new land that exists on the other side of a rabbit hole. An invisible cat, a hookah smoking caterpillar and playing-cards that talk are just some of the fantastic things she\'s seen during this impossible adventure. Surely this troubled girl must be insane, and her doctors aim to cure her with a treatment that will make her forget everything. Alice seems ready to put it all behind her, especially the painful memory of the genie she fell in love with and lost forever -- the handsome and mysterious Cyrus . But deep down Alice knows this world is real, and just in the nick of time the sardonic Knave of Hearts and the irrepressible White Rabbit arrive to save her from a doomed fate. Together the trio will take a tumble down the rabbit hole to this Wonderland where nothing is impossible.</p>',
      updated: 1575358030,
      _links: [Object] },
    { id: 13,
      url: 'https://www.tvmaze.com/shows/62/the-originals',
      name: 'The Originals',
      type: 'Scripted',
      language: 'English',
      genres: [Array],
      status: 'Ended',
      runtime: 60,
      premiered: '2013-10-03',
      officialSite: 'https://www.cwtv.com/shows/the-originals/',
      schedule: [Object],
      rating: [Object],
      weight: 87,
      network: [Object],
      webChannel: null,
      externals: [Object],
      image: [Object],
      summary:
       '<p><b>The Originals</b> is a spin-off show from the supernatural drama <i>The Vampire Diaries</i>. It is based in the city of New Orleans where the originals represent the original vampires. The show is primarily based around conflict between vampires, werewolves and witches in the city.</p>',
      updated: 1575540921,
      _links: [Object] },
    { id: 14,
      url: 'https://www.tvmaze.com/shows/48/madam-secretary',
      name: 'Madam Secretary',
      type: 'Scripted',
      language: 'English',
      genres: [Array],
      status: 'Ended',
      runtime: 60,
      premiered: '2014-09-21',
      officialSite: 'https://www.cbs.com/shows/madam-secretary/',
      schedule: [Object],
      rating: [Object],
      weight: 100,
      network: [Object],
      webChannel: null,
      externals: [Object],
      image: [Object],
      summary:
       '<p><b>Madam Secretary</b> follows Elizabeth McCord, the shrewd, determined, newly appointed Secretary of State who drives international diplomacy, battles office politics and circumvents protocol as she negotiates global and domestic issues, both at the White House and at home. A college professor and a brilliant former CIA analyst who left for ethical reasons, Elizabeth returns to public life at the request of the President following the suspicious death of her predecessor. The President values her apolitical leanings, her deep knowledge of the Middle East, her flair for languages and her ability to not just think outside the box, but to not even acknowledge there is a box.</p>',
      updated: 1576063638,
      _links: [Object] },
    { id: 15,
      url: 'https://www.tvmaze.com/shows/208/the-chair',
      name: 'The Chair',
      type: 'Reality',
      language: 'English',
      genres: [],
      status: 'Ended',
      runtime: 60,
      premiered: '2014-09-06',
      officialSite: null,
      schedule: [Object],
      rating: [Object],
      weight: 0,
      network: [Object],
      webChannel: null,
      externals: [Object],
      image: [Object],
      summary:
       '<p><b>The Chair</b> is a competition documentary series that follows two directors through the process of bringing their first feature to the screen. The up-and-coming directors, who have unique backgrounds and skill sets, will be provided with an identical screenplay which they must craft as their own film. <i>The Chair</i> will document the creation, marketing and theatrical release of both adaptations, which will also air on STARZ. Both directors will be given the same budget, and both versions will use locations in the same city. Through multiplatform voting, the audience will determine which director will be awarded $250,000.</p>',
      updated: 1573497558,
      _links: [Object] },
    { id: 16,
      url: 'https://www.tvmaze.com/shows/171/how-i-met-your-mother',
      name: 'How I Met Your Mother',
      type: 'Scripted',
      language: 'English',
      genres: [Array],
      status: 'Ended',
      runtime: 30,
      premiered: '2005-09-19',
      officialSite: 'https://www.cbs.com/shows/how_i_met_your_mother',
      schedule: [Object],
      rating: [Object],
      weight: 95,
      network: [Object],
      webChannel: null,
      externals: [Object],
      image: [Object],
      summary:
       '<p><b>How I Met Your Mother</b> is a comedy about Ted and how he fell in love. It all starts when Ted\'s best friend, Marshall drops the bombshell that he\'s going to propose to his long-time girlfriend, Lilya kindergarten teacher. At that moment, Ted realizes that he had better get a move on if he too hopes to find true love. Helping him in his quest is Barney a friend with endless, sometimes outrageous opinions, a penchant for suits and a foolproof way to meet women. When Ted meets Robin he\'s sure it\'s love at first sight, but destiny may have something else in store.</p>',
      updated: 1573150338,
      _links: [Object] },
    { id: 17,
      url: 'https://www.tvmaze.com/shows/52/how-to-get-away-with-murder',
      name: 'How to Get Away with Murder',
      type: 'Scripted',
      language: 'English',
      genres: [Array],
      status: 'Running',
      runtime: 60,
      premiered: '2014-09-25',
      officialSite: 'https://abc.go.com/shows/how-to-get-away-with-murder',
      schedule: [Object],
      rating: [Object],
      weight: 98,
      network: [Object],
      webChannel: null,
      externals: [Object],
      image: [Object],
      summary:
       '<p>The brilliant, charismatic and seductive Professor Annalise Keating gets entangled with four law students from her class, <b>How to Get Away with Murder</b>. Little do they know that they will have to apply what they learned to real life, in this masterful, sexy, suspense-driven legal thriller.</p>',
      updated: 1577255126,
      _links: [Object] },
    { id: 18,
      url: 'https://www.tvmaze.com/shows/236/gcb',
      name: 'GCB',
      type: 'Scripted',
      language: 'English',
      genres: [Array],
      status: 'Ended',
      runtime: 60,
      premiered: '2012-03-04',
      officialSite: 'https://abc.go.com/shows/gcb',
      schedule: [Object],
      rating: [Object],
      weight: 0,
      network: [Object],
      webChannel: null,
      externals: [Object],
      image: [Object],
      summary:
       '<p>Amanda Vaughn once the ultimate high school "mean girl", is forced to return home in disgrace after her marriage ends in scandal. Amanda is nothing like the girl she was 20 years ago, but as her old classmates reacquaint themselves with the new Amanda, will her home town welcome her with open arms or seek revenge? No one in this town is a saint, but that doesn\'t mean they can\'t have a heart. As Amanda and her teenage kids try to adjust to their new lives, the ladies from her past alternate between sympathy and scheming.</p>',
      updated: 1573226209,
      _links: [Object] },
    { id: 19,
      url: 'https://www.tvmaze.com/shows/31/marvels-agents-of-shield',
      name: 'Marvel\'s Agents of S.H.I.E.L.D.',
      type: 'Scripted',
      language: 'English',
      genres: [Array],
      status: 'Running',
      runtime: 60,
      premiered: '2013-09-24',
      officialSite: 'https://abc.go.com/shows/marvels-agents-of-shield',
      schedule: [Object],
      rating: [Object],
      weight: 99,
      network: [Object],
      webChannel: null,
      externals: [Object],
      image: [Object],
      summary:
       '<p>Phil Coulson heads an elite team of fellow agents with the worldwide law-enforcement organization known as S.H.I.E.L.D. (Strategic Homeland Intervention Enforcement and Logistics Division), as they investigate strange occurrences around the globe. Its members -- each of whom brings a specialty to the group -- work with Coulson to protect those who cannot protect themselves from extraordinary and inconceivable threats.</p>',
      updated: 1574328665,
      _links: [Object] },
    { id: 20,
      url: 'https://www.tvmaze.com/shows/124/2-broke-girls',
      name: '2 Broke Girls',
      type: 'Scripted',
      language: 'English',
      genres: [Array],
      status: 'Ended',
      runtime: 30,
      premiered: '2011-09-19',
      officialSite: 'https://www.cbs.com/shows/2_broke_girls/',
      schedule: [Object],
      rating: [Object],
      weight: 91,
      network: [Object],
      webChannel: null,
      externals: [Object],
      image: [Object],
      summary:
       '<p><b>2 Broke Girls</b> is a comedy about two young women waitressing at a greasy spoon diner who strike up an unlikely friendship in the hopes of launching a successful business - if only they can raise the cash. Sassy, streetwise Max Black works two jobs just to get by, one of which is waiting tables during the night shift at the retro-hip Williamsburg Diner. Sophisticated Caroline Channing is an uptown trust fund princess who\'s having a run of bad luck that forces her to reluctantly give waitressing a shot. At first, Max sees Caroline as yet another in a long line of inept servers she must cover for, but she\'s surprised to find that Caroline has as much substance as she does style.</p><p>When Caroline discovers Max\'s knack for baking amazing cupcakes, she sees a lucrative future for them, but first they need to raise the start-up money. While they save their tips, they\'ll stay at the restaurant, working with Oleg, an overly flirtatious Russian cook; Earl, a 75-year-old kool-kat cashier; and Han Lee, the new, eager-to-please owner of the diner. Working together, these two broke girls living in one expensive city might just find the perfect recipe for their big break.</p>',
      updated: 1573517220,
      _links: [Object] }
   ] }